services:
  quiz.api:
    container_name: quiz-test.api
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.quiz-test-api.rule=Host(`quiz-test-api.nh9.dev`)"
      - "traefik.http.routers.quiz-test-api.entrypoints=web"
    networks:
      - web

networks:
  web:
    external:
      name: traefik-net
